---
- name: httpd service
  hosts: prod
  tasks:

  - name: httpd is present
    yum: 
      name: httpd
      state: present
  
  - name: index file
    copy:
      src: /root/ansible_inventory/sample.txt
      dest: /temp/
  - name: httpd is started
    service:
      name: httpd
      state: started
      enabled: true


...
